version: "3.9"
services:
  db:
    image: postgres:16
    container_name: resourcehub-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_resources
    ports:
      - "5432:5432"        
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: resourcehub-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 8000
      JWT_SECRET: dev_secret_change_later
      DATABASE_URL: postgresql://postgres:postgres@db:5432/student_resources
    ports:
      - "8000:8000"
   
volumes:
  dbdata:
